tap "buo/cask-upgrade"
tap "candid82/brew"
tap "caskroom/fonts"
tap "dteoh/devdocs"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "josh-/qlscpt"
tap "keith/formulae"
tap "lukakerr/casks"
tap "sambadevi/powerlevel9k"
tap "timothyye/tap"
tap "yqrashawn/goku"
brew "advancecomp"
brew "python"
brew "icu4c"
brew "archey"
brew "autoconf-archive"
brew "automake"
brew "axel"
brew "bash"
brew "bash-completion"
brew "bat"
brew "blueutil"
brew "brainfuck"
brew "cataclysm"
brew "ccat"
brew "cmake"
brew "cmatrix"
brew "cookiecutter"
brew "coreutils"
brew "cowsay"
brew "curseofwar"
brew "darksky-weather"
brew "diffuse"
brew "emacs"
brew "libtool"
brew "graphviz"
brew "pkg-config"
brew "evince"
brew "fd"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gifsicle"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "glances"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "googler"
brew "haskell-stack"
brew "hstr"
brew "htop"
brew "imagemagick"
brew "inetutils"
brew "klavaro"
brew "kubernetes-cli"
brew "leptonica"
brew "libgit2"
brew "llvm"
brew "lolcat"
brew "lsof"
brew "luarocks"
brew "mackup"
brew "macvim", link: false
brew "mas"
brew "micro"
brew "midnight-commander"
brew "mit-scheme"
brew "mosh"
brew "mpg123"
brew "nano"
brew "neovim"
brew "nethack"
brew "ninja"
brew "node"
brew "openssh"
brew "pandoc"
brew "pdfgrep"
brew "pipenv"
brew "pngquant", args: ["HEAD"]
brew "progress"
brew "pv"
brew "qalculate-gtk"
brew "qemu"
brew "r"
brew "rakudo-star"
brew "ranger"
brew "redis"
brew "remind"
brew "ripgrep"
brew "rlwrap"
brew "ruby"
brew "screenfetch"
brew "shellcheck"
brew "siege"
brew "spark"
brew "speedtest-cli"
brew "supervisor"
brew "tcl-tk"
brew "tesseract"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "vim"
brew "vitetris", link: false
brew "watson"
brew "wget"
brew "wifi-password"
brew "xdot"
brew "zlib"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "jesseduffield/lazygit/lazygit"
brew "keith/formulae/reminders-cli"
brew "timothyye/tap/ydict"
brew "yqrashawn/goku/goku"
cask "airdroid"
cask "alfred"
cask "anaconda"
cask "anki"
cask "anybar"
cask "aria2gui"
cask "astropad"
cask "avira-antivirus"
cask "background-music"
cask "bbedit"
cask "beaker-browser"
cask "betterandbetter"
cask "bilibili"
cask "blender"
cask "blockblock"
cask "calibre"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "devdocs"
cask "digikam"
cask "do-not-disturb"
cask "docker"
cask "dozer"
cask "drawio"
cask "duet"
cask "emacs"
cask "ezip"
cask "find-any-file"
cask "firefox"
cask "flash-npapi"
cask "flash-ppapi"
cask "fliqlo"
cask "flux"
cask "font-genjyuugothic"
cask "font-genshingothic"
cask "font-noto-sans-cjk-sc"
cask "font-noto-serif-cjk-sc"
cask "font-source-code-pro"
cask "fork"
cask "free-download-manager"
cask "freecad"
cask "geany"
cask "gimp"
cask "github"
cask "gnucash"
cask "google-chrome-beta"
cask "gpodder"
cask "hammerspoon"
cask "handbrake"
cask "haroopad"
cask "icons8"
cask "ieasemusic"
cask "iina"
cask "imageoptim"
cask "insomnia"
cask "intel-power-gadget"
cask "iterm2"
cask "java"
cask "julia"
cask "kap"
cask "karabiner-elements"
cask "kdiff3"
cask "kextviewr"
cask "keyboard-maestro"
cask "keyboardcleantool"
cask "keycastr"
cask "kindlegen"
cask "knockknock"
cask "lantern"
cask "latest"
cask "launchbar"
cask "libreoffice"
cask "libreoffice-language-pack"
cask "licecap"
cask "listen1"
cask "lulu"
cask "macdown"
cask "macs-fan-control"
cask "mactex"
cask "macvim"
cask "mongodb"
cask "motrix"
cask "mtmr"
cask "mysqlworkbench"
cask "neteasemusic"
cask "nutstore"
cask "obs"
cask "omnidisksweeper"
cask "onyx"
cask "opera"
cask "oracle-jdk"
cask "oversight"
cask "pencil2d"
cask "phew"
cask "platypus"
cask "podcastmenu"
cask "pomotodo"
cask "popmaker"
cask "powershell-preview"
cask "prefs-editor"
cask "pycharm-ce"
cask "qladdict"
cask "qlcolorcode"
cask "qldds"
cask "qlgradle"
cask "qlimagesize"
cask "qlplayground"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "rcdefaultapp"
cask "redis"
cask "reggy"
cask "reikey"
cask "rescuetime"
cask "selfcontrol"
cask "sequel-pro-nightly"
cask "setapp"
cask "showyedge"
cask "shuttle"
cask "skim"
cask "sloth"
cask "snipaste"
cask "sourcetree"
cask "squirrel"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "suspicious-package"
cask "syncthing"
cask "taskexplorer"
cask "teamviewer"
cask "terminus"
cask "textmate"
cask "thunderbird"
cask "tickeys"
cask "typora"
cask "unicodechecker"
cask "upterm"
cask "usage"
cask "vagrant"
cask "vimr"
cask "visual-studio-code"
cask "vlc"
cask "wewechat"
cask "whatpulse"
cask "wireshark"
cask "wiznote"
cask "workflowy"
cask "xquartz"
cask "zotero"
cask "josh-/qlscpt/qlscpt"
cask "lukakerr/casks/pine"
mas "Astrvm.Vitriolvm.QR-CreatorMini", id: 1185353935
mas "at.EternalStorms.Yoink", id: 457622435
mas "at.obdev.MicroSnitch", id: 972028355
mas "au.id.haroldchu.mac.Bandwidth", id: 490461369
mas "build.bru.MacGladys", id: 1382386877
mas "cn.futu.NiuniuPro", id: 1058271449
mas "co.circleapps.sourceplayerlite", id: 1444389594
mas "co.fluder.FSNotes", id: 1277179284
mas "co.noteplan.NotePlan", id: 1137020764
mas "com.3Planesoft.DigitalClock3D", id: 661632558
mas "com.3Planesoft.Earth3D", id: 476566660
mas "com.agiletortoise.Drafts-OSX", id: 1435957248
mas "com.alice.mac.go2shell", id: 445770608
mas "com.amazon.Kindle", id: 405399194
mas "com.aone.keka", id: 470158793
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iBooksAuthor", id: 490152466
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.ashen.iosdevtools", id: 1445645840
mas "com.atlassian.trello", id: 1278508951
mas "com.autodesk.sketchbookpro7mac", id: 863486266
mas "com.betafish.adblock-mac", id: 1402042596
mas "com.bitwarden.desktop", id: 1352778147
mas "com.bjango.istatmenus.mas", id: 1319778037
mas "com.blackmagic-design.DiskSpeedTest", id: 425264550
mas "com.byteamaze.osx.amazephotos", id: 1441404964
mas "com.chintanghate.Notes-Exporter", id: 1099120373
mas "com.completemagic.magicsortlist", id: 883969157
mas "com.coppertino.Vox", id: 461369673
mas "com.corona.SIDTOSX", id: 1308724728
mas "com.coteditor.CotEditor", id: 1024640650
mas "com.ctmdev.App-Language-Chooser", id: 451732904
mas "com.daisydiskapp.DaisyDisk", id: 411643860
mas "com.dejal.timeout.free", id: 402592703
mas "com.dhtech.mac.Wallpaper", id: 1214761683
mas "com.eltima.cmd1.mas", id: 1035236694
mas "com.eusoft.eudic", id: 402380914
mas "com.eusoft.ting-mac-en", id: 734383760
mas "com.fiplab.shortcutbar", id: 1148891783
mas "com.hanwe.DefaultLanguage", id: 1453278898
mas "com.happy2tap.Recordings", id: 1017198069
mas "com.hewbo.hexeditor", id: 909566003
mas "com.if.Amphetamine", id: 937984704
mas "com.iflytek.macinput", id: 1243368435
mas "com.imthekingofmac.ZoomMe", id: 1437487517
mas "com.ipermanent.classmaker", id: 1076223220
mas "com.iqiyi.player", id: 1012296988
mas "com.JadenGeller.Helium", id: 1054607607
mas "com.jgronek.Launchey-2", id: 1365625021
mas "com.jmitch.heliumlift", id: 1018899653
mas "com.joshjacob.qrjournal", id: 483820530
mas "com.jumsoft.infographics", id: 577411683
mas "com.kfir.mac20486x6", id: 892912527
mas "com.kyome.RunCat", id: 1429033973
mas "com.liupeng.mac.FinderMenu", id: 1162194131
mas "com.lllteam.QuickMoveFile.Pro", id: 1414457383
mas "com.macpawlabs.appbebackmas", id: 1317253465
mas "com.manytricks.Keymo", id: 449863619
mas "com.manytricks.Moom", id: 419330170
mas "com.manytricks.TimeSinkClient", id: 404363161
mas "com.mathpix.snipping-tool", id: 1349670778
mas "com.microsoft.Excel", id: 462058435
mas "com.microsoft.Powerpoint", id: 462062816
mas "com.microsoft.protection.rms-sharing-mac", id: 908570259
mas "com.microsoft.Word", id: 462054704
mas "com.mindfulnessbellmenubar.ios", id: 1144260305
mas "com.naarak.ScherlokkLite", id: 918486500
mas "com.ookla.speedtest-macos", id: 1153157709
mas "com.pilotmoon.popclip", id: 445189367
mas "com.pointum.hazeover", id: 430798174
mas "com.qiyi.UniversalPlayerMac", id: 1331844018
mas "com.readdle.smartemail-Mac", id: 1176895641
mas "com.renfei.SnippetsLab", id: 1006087419
mas "com.ridiculousfish.HexFiend", id: 1342896380
mas "com.shawn.jsonmodeler", id: 1143129421
mas "com.skitch.skitch", id: 425955336
mas "com.soponext.multibrowser", id: 1183559550
mas "com.syniumsoftware.macfamilytree8", id: 1037755919
mas "com.tencent.JietuMac", id: 1059334054
mas "com.tencent.miniqpicview", id: 1314842898
mas "com.tencent.qq", id: 451108668
mas "com.tencent.QQMusicMac", id: 595615424
mas "com.tencent.WeWorkMac", id: 1189898970
mas "com.tencent.xinWeChat", id: 836500024
mas "com.termius.mac", id: 1176074088
mas "com.tunabellysoftware.spellingalphabet", id: 499351638
mas "com.txtlabs.screenshotpsd", id: 489880259
mas "com.vklyusko.KeyboardLocker", id: 1444996429
mas "com.wolfrosch.Gapplin", id: 768053424
mas "com.wunderkinder.wunderlistdesktop", id: 410628904
mas "com.wutian.weibo", id: 789066512
mas "com.xwavesoft.cloudoutlinertwomaclite", id: 1066183430
mas "com.yinxiang.Mac", id: 1356055347
mas "com.youku.mac", id: 1014945607
mas "com.zoomnotes.ZoomNotesX", id: 986761220
mas "cx.c3.theunarchiver", id: 425424353
mas "de.APPenzeller.PiPifier", id: 1160374471
mas "de.codingmonkeys.SubEthaEdit.Mac", id: 728530824
mas "de.pecora.iClock", id: 508034739
mas "imagetasks.iStatistica", id: 1025822138
mas "io.hyperapp.XcodeCleaner", id: 1296084683
mas "net.iyingyue.mac", id: 1050489667
mas "net.toolinbox.ihosts", id: 1102004240
mas "org.adblockplus.adblockplussafarimac", id: 1432731683
mas "org.brunovandekerkhove.mirror", id: 985134131
mas "org.sunjw.fHashMacUI", id: 1055555711
mas "ru.keepcoder.Telegram", id: 747648890
mas "tech.miidii.TakeABreak", id: 1457158844
mas "tech.miidii.UTC-Mac", id: 1454211033
mas "whbalzac.SiShi-macOS", id: 1416483550
